export const BlogPosts = [
  {
    id: 1,
    title: 'How Real-Time Analytics Transformed a Retail Chain',
    slug: 'how-real-time-analytics-transformed-retail-chain',
    excerpt: 'Learn how a major retail chain increased revenue by 32% using real-time analytics to optimize inventory and pricing.',
    content: '',
    date: 'May 15, 2025',
    category: 'Case Study',
    image: 'https://images.pexels.com/photos/3184338/pexels-photo-3184338.jpeg',
    author: {
      name: 'Sarah Johnson',
      avatar: 'https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg',
    },
  },
  {
    id: 2,
    title: '7 Dashboard Design Principles for Better Data Visualization',
    slug: '7-dashboard-design-principles-better-data-visualization',
    excerpt: 'Create more effective dashboards with these proven design principles that enhance data comprehension and decision-making.',
    content: '',
    date: 'May 10, 2025',
    category: 'Design',
    image: 'https://images.pexels.com/photos/669615/pexels-photo-669615.jpeg',
    author: {
      name: 'Michael Chen',
      avatar: 'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg',
    },
  },
  {
    id: 3,
    title: 'The Future of Business Intelligence: AI-Powered Analytics',
    slug: 'future-business-intelligence-ai-powered-analytics',
    excerpt: 'Explore how artificial intelligence is revolutionizing business intelligence and creating new opportunities for data-driven decisions.',
    content: '',
    date: 'May 5, 2025',
    category: 'Technology',
    image: 'https://images.pexels.com/photos/3183150/pexels-photo-3183150.jpeg',
    author: {
      name: 'Jessica Martinez',
      avatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg',
    },
  },
  {
    id: 4,
    title: 'Data Security Best Practices for Analytics Platforms',
    slug: 'data-security-best-practices-analytics-platforms',
    excerpt: 'Protect your business data with these essential security protocols and compliance strategies for modern analytics platforms.',
    content: '',
    date: 'April 28, 2025',
    category: 'Security',
    image: 'https://images.pexels.com/photos/60504/security-protection-anti-virus-software-60504.jpeg',
    author: {
      name: 'David Wilson',
      avatar: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg',
    },
  },
  {
    id: 5,
    title: 'How to Build a Data-Driven Culture in Your Organization',
    slug: 'build-data-driven-culture-organization',
    excerpt: 'Transform your company culture to embrace data at every level with these strategies from successful organizations.',
    content: '',
    date: 'April 22, 2025',
    category: 'Leadership',
    image: 'https://images.pexels.com/photos/3182812/pexels-photo-3182812.jpeg',
    author: {
      name: 'Sarah Johnson',
      avatar: 'https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg',
    },
  },
  {
    id: 6,
    title: 'Integrating Multiple Data Sources: Challenges and Solutions',
    slug: 'integrating-multiple-data-sources-challenges-solutions',
    excerpt: 'Overcome common obstacles when integrating data from various sources to create a unified analytics platform.',
    content: '',
    date: 'April 15, 2025',
    category: 'Technical',
    image: 'https://images.pexels.com/photos/373543/pexels-photo-373543.jpeg',
    author: {
      name: 'Michael Chen',
      avatar: 'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg',
    },
  },
];